//! # revm-interpreter
//!
//! Interpreter is part of the project that executes EVM instructions.
#![cfg_attr(not(test), warn(unused_crate_dependencies))]
#![cfg_attr(not(feature = "std"), no_std)]

#[cfg(not(feature = "std"))]
extern crate alloc as std;

#[macro_use]
mod macros;

/// Gas calculation utilities and constants.
pub mod gas;
/// Context passed to instruction implementations.
pub mod instruction_context;
/// Instruction execution results and success/error types.
mod instruction_result;
/// EVM instruction implementations organized by category.
pub mod instructions;
/// Core interpreter implementation for EVM bytecode execution.
pub mod interpreter;
/// Types for interpreter actions like calls and contract creation.
pub mod interpreter_action;
/// Type traits and definitions for interpreter customization.
pub mod interpreter_types;
/// Host-only EVM basic-block fingerprint logger. No-op on zkvm targets.
pub mod bb_log;
/// Build-time AOT table for transpiled EVM basic blocks, keyed by
/// `(code_hash, pc)`. Auto-generated by canonical-gas. Definitions of
/// `AotEntry` / `AotKind` live in `aot_table_types`.
#[cfg(feature = "evm-aot")]
pub mod aot_table;
pub mod aot_table_types;
/// Generic basic-block walker: runs a pre-analyzed pure BB by reading
/// opcodes from bytecode and dispatching them via a small match. Used by
/// the `evm-bb-aot` path.
#[cfg(feature = "evm-bb-aot")]
pub mod bb_walker;
/// Auto-generated per-`(code_hash, pc)` dispatch table for the generic-BB
/// walker. Overwritten by `canonical-gas --emit-bb-aot-table` or
/// `canonical-gas --emit-bb-shapes`. The two emitters produce the same
/// file but with different `BbWalkerEntry` fields (`desc` vs `shape_id`).
#[cfg(feature = "evm-bb-aot")]
pub mod bb_walker_table;
/// Auto-generated per-shape handler functions and `dispatch_shape`.
/// Used by step() when an evm-bb-aot lookup hits.
#[cfg(feature = "evm-bb-aot")]
pub mod aot_bb_shapes;
/// Inline-friendly per-opcode helpers used by AOT shape handlers (skip
/// revm's popn_top local-copy + function-call boundary).
#[cfg(feature = "evm-bb-aot")]
pub mod bb_ops;

// Reexport primary types.
pub use context_interface::{
    cfg::gas::InitialAndFloorGas,
    context::{SStoreResult, SelfDestructResult, StateLoad},
    host, CreateScheme, Host,
};
pub use gas::Gas;
pub use instruction_context::InstructionContext;
pub use instruction_result::*;
pub use instructions::{instruction_table, Instruction, InstructionTable};
pub use interpreter::{
    num_words, InputsImpl, Interpreter, InterpreterResult, SharedMemory, Stack, STACK_LIMIT,
};
pub use interpreter_action::{
    CallInput, CallInputs, CallOutcome, CallScheme, CallValue, CreateInputs, CreateOutcome,
    FrameInput, InterpreterAction,
};
pub use interpreter_types::InterpreterTypes;
